"""Public local plugin API v3 for image-downloader."""

from .config import AppConfig, apply_overrides, load_application_config
from .exceptions import (
    AuthenticationError,
    ConfigurationError,
    DownloaderError,
    InterProcessLockError,
    PluginError,
    SecretNotFound,
    StorageSafetyError,
    UnsupportedSiteFeature,
)
from .models import (
    Chapter,
    ChapterResult,
    DownloadManifest,
    DownloadResult,
    FailureKind,
    ImageArtifact,
    ImageFailure,
    ImageOutcome,
    ImageOutcomeKind,
    ImageResource,
    ImageSaveOptions,
    RequestResponse,
    RequestSpec,
    UpdateCandidate,
    UpdateChange,
    UpdateChangeKind,
    UpdateResult,
    UpdateSnapshot,
)
from .ports import (
    AuthFlow,
    ConfigurableSitePlugin,
    ImageProcessor,
    OriginScopedAuthFlow,
    PluginExecutionContext,
    RequestPort,
    SecretProvider,
    SitePlugin,
    TransformContext,
    UpdateProvider,
)
from .runtime import DownloadService, RuntimeComposer

__all__ = [
    "AppConfig",
    "apply_overrides",
    "AuthFlow",
    "AuthenticationError",
    "Chapter",
    "ChapterResult",
    "ConfigurableSitePlugin",
    "ConfigurationError",
    "DownloadManifest",
    "DownloadResult",
    "DownloadService",
    "DownloaderError",
    "FailureKind",
    "ImageArtifact",
    "ImageFailure",
    "ImageOutcome",
    "ImageOutcomeKind",
    "ImageProcessor",
    "ImageResource",
    "ImageSaveOptions",
    "InterProcessLockError",
    "load_application_config",
    "OriginScopedAuthFlow",
    "PluginError",
    "PluginExecutionContext",
    "RequestPort",
    "RequestResponse",
    "RequestSpec",
    "RuntimeComposer",
    "SecretNotFound",
    "SecretProvider",
    "SitePlugin",
    "StorageSafetyError",
    "TransformContext",
    "UnsupportedSiteFeature",
    "UpdateCandidate",
    "UpdateChange",
    "UpdateChangeKind",
    "UpdateProvider",
    "UpdateResult",
    "UpdateSnapshot",
]
