"""Public compatibility imports for plugin security and runtime management."""

from .plugins.lifecycle import (
    PluginClassLoader,
    PluginDiagnostic,
    PluginDiscovery,
    PluginDiscoveryResult,
    PluginManifestVerifier,
    PluginRecord,
    PluginRegistry,
    PluginVerificationResult,
)
from .plugins.management import (
    PluginUninstallResult,
    catalog_entry_for,
    install_plugin,
    revoke_plugin,
    trust_plugin,
    uninstall_plugin,
)
from .plugins.plugin_manifest import (
    CatalogEntry,
    PluginCatalog,
    PluginConfigOverrides,
    PluginKind,
    PluginManifest,
    PluginVerificationMode,
    PluginVerificationOverride,
    author_config,
    canonical_jcs,
    catalog_path,
    effective_verification_mode,
    plugin_content_digest,
    read_manifest,
    verify_manifest,
    verify_signed_plugin_source,
    write_catalog,
)
from .plugins.runtime import PluginRuntime, PluginSelector, safe_app_settings

__all__ = [
    "CatalogEntry",
    "PluginCatalog",
    "PluginConfigOverrides",
    "PluginKind",
    "PluginManifest",
    "PluginVerificationMode",
    "PluginVerificationOverride",
    "PluginClassLoader",
    "PluginDiagnostic",
    "PluginDiscovery",
    "PluginDiscoveryResult",
    "PluginManifestVerifier",
    "PluginRecord",
    "PluginRegistry",
    "PluginVerificationResult",
    "PluginRuntime",
    "PluginSelector",
    "safe_app_settings",
    "catalog_entry_for",
    "install_plugin",
    "revoke_plugin",
    "trust_plugin",
    "uninstall_plugin",
    "PluginUninstallResult",
    "author_config",
    "canonical_jcs",
    "catalog_path",
    "effective_verification_mode",
    "plugin_content_digest",
    "read_manifest",
    "verify_manifest",
    "verify_signed_plugin_source",
    "write_catalog",
]
